### ISSUE TITLE
Falling back to password authentication silently when no keys available

### ISSUE THREAD

**Issue by ghosgitAurea** [alair-aurea/ansible-scripts#22]
If no key is added to keys directory and the user selects key file to be used, the scripts prompts password entry. If there is no key in 'keys' directory warning can be shown to user and show the prompt again so user can copy the pem file to 'keys' directory can move on.

**Comment by alair-aurea** [comment]
If there is no file in the keys directory or if it is missing, we are falling back to password authentication silently. The suggested approach is better.
