### ISSUE TITLE
Add support for UI interaction provisioning

### ISSUE THREAD

**Issue by alair-aurea** [alair-aurea/ansible-scripts#3]
Some windows programs require input from the user using the UI. How Ansible can install such programs? Options:

1. Chocolatey: https://chocolatey.org/
    -  Ansible offers support for it: https://docs.ansible.com/ansible/2.5/modules/win_chocolatey_module.html#win-chocolatey-module

2. Provisioning Packages : https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-packages

**Comment by ghosgitAurea** [comment]
I think ansible can give manual selections as as list when starting silent installer.

**Comment by alair-aurea** [comment]
But is the installation packaged required to provide some standard interface or it works with all types of installation?

**Comment by alair-aurea** [comment]
Not necessary considering the current set of tools. All of them could be installed without UI interaction.
